# Generated by Django 3.0.4 on 2020-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_chair', models.BooleanField()),
                ('is_on_oc', models.BooleanField()),
                ('conference', models.ManyToManyField(to='events.Conference')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='organizers',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.AddField(
            model_name='company',
            name='people',
            field=models.ManyToManyField(blank=True, to='events.Person'),
        ),
    ]
